name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc libxml2-utils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PYTHONPATH: ${{ github.workspace }}/src

      - name: Run environment check
        run: python src/scripts/env_check.py

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest tests/test_converter.py
          pytest tests/test_tei.py

      - name: Build EPUB
        run: bash scripts/build_epub.sh

      - name: Validate TEI (skipped until schema configured)
        if: ${{ false }}
        run: bash scripts/validate_tei.sh
