name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run environment check
        run: python src/scripts/env_check.py

      - name: Run tests
        run: |
          pytest tests/test_converter.py
          pytest tests/test_tei.py

      - name: Build EPUB
        run: bash scripts/build_epub.sh

      - name: Validate TEI
        run: bash scripts/validate_tei.sh