name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site artifacts
        run: |
          rm -rf site
          export PYTHONPATH="$PWD/src"
          python -m german_book_converter.cli \
            --input data/raw/wellmann.html \
            --output site \
            --skip-epub \
            --with-viewer
          # Add a simple index linking to the viewer and embedded view
          cat > site/index.html << 'HTML'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Apographon Preview</title>
            <style>body{font:16px/1.5 system-ui,Segoe UI,Roboto,Ubuntu,sans-serif;margin:2rem;}</style>
          </head>
          <body>
            <h1>Apographon Preview</h1>
            <ul>
              <li><a href="viewer.html">Viewer (autoloads cleaned.html)</a></li>
              <li><a href="view.html">Embedded View (no fetch)</a></li>
              <li><a href="output.xml">TEI (rendered via XSL)</a></li>
              <li><a href="cleaned.html">Cleaned HTML</a></li>
            </ul>
          </body>
          </html>
          HTML

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
